[project]
name = "enigma"
version = "0.1.0"
description = "This project is a python code replica of the German Encryption machine Enigma."
readme = "README.md"
authors = [
    { name = "Vineet Gaira", email = "vineetgaira1729@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
enigma = "enigma:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
