[project]
name = "enigma"
version = "0.1.0"
description = "This project is a python code replica of the German Encryption machine Enigma."
readme = "README.md"
authors = [
    { name = "Vineet Gaira", email = "vineetgaira1729@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=9.1.1",
    "typer>=0.27.2",
]

[project.scripts]
enigma = "enigma:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
