# This stores historical rotor wiring and reflector wiring as constants.

ROTOR_I   = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
ROTOR_II  = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
ROTOR_III = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
NOTCH_I, NOTCH_II, NOTCH_III = "Q", "E", "V"
REFLECTOR_B = "YRUHQSLDPXNGOKMIEBFZCWVJAT"